/home/wg25r/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:216: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn(
Traceback (most recent call last):
  File "/home/wg25r/gas_dino/main.py", line 281, in <module>
    "X_val": wandb.Image(X_val[0][:3].cpu().detach().numpy()),
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 180, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 325, in _initialize_from_data
    self.to_uint8(data), mode=mode or self.guess_mode(data)
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 485, in guess_mode
    raise ValueError(
ValueError: Un-supported shape for image conversion [3, 448, 448]
Traceback (most recent call last):
  File "/home/wg25r/gas_dino/main.py", line 281, in <module>
    "X_val": wandb.Image(X_val[0][:3].cpu().detach().numpy()),
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 180, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 325, in _initialize_from_data
    self.to_uint8(data), mode=mode or self.guess_mode(data)
  File "/home/wg25r/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 485, in guess_mode
    raise ValueError(
ValueError: Un-supported shape for image conversion [3, 448, 448]
